In [4]:
import pandas as pd
import numpy as np

# 载入AAindex数据
def load_aaindex(filepath):
    return pd.read_csv(filepath)

# 根据AAindex矩阵和蛋白质序列进行编码
def encode_protein(sequence, aaindex):
    encoded_features = []
    for amino_acid in sequence:
        if amino_acid in aaindex.columns:
            # 将每个氨基酸的AAindex值添加到特征列表中
            encoded_features.append(aaindex[amino_acid].values)
        else:
            # 如果某个氨基酸在AAindex中没有对应的列，可以添加一个全0向量
            # 这个向量的长度应该与其他特征向量长度相同
            encoded_features.append(np.zeros(aaindex.shape[0]))
    return np.array(encoded_features)

# 示例
filepath = 'aaindex1.csv'  # AAindex文件路径
aaindex = load_aaindex(filepath)  # 加载AAindex数据

# 假设你有一个蛋白质序列
protein_sequence = "ADEFGHIKLMNPQRSTVWY"  # 示例序列

# 编码蛋白质序列
encoded_sequence = encode_protein(protein_sequence, aaindex)
print(encoded_sequence.shape,encoded_sequence)


(19, 566) [[ 4.35   0.61   1.18  ...  0.     6.     0.   ]
 [ 4.76   0.46   0.05  ...  0.    10.4    2.969]
 [ 4.29   0.47   0.11  ...  0.    10.667  1.822]
 ...
 [ 3.95   1.32   1.08  ...  0.     9.     6.   ]
 [ 4.7    2.65   0.77  ...  0.211 12.75   2.044]
 [ 4.6    1.88   0.39  ... -0.96  12.222  1.599]]


In [6]:
from kan import *


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

# initialize KAN with G=3
model = KAN(width=[2,1,1], grid=3, k=3, seed=1)

# create dataset
f = lambda x: torch.exp(torch.sin(torch.pi*x[:,[0]]) + x[:,[1]]**2)
dataset = create_dataset(f, n_var=2)


cuda
checkpoint directory created: ./model
saving model version 0.0


In [9]:
dataset['train_input'].shape

torch.Size([1000, 2])